[package]
name = "oxdock-buildtime-macros"
description = "Compile-time macros for bundling assets using OxDock's Dockerfile-inspired DSL."
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
anyhow.workspace = true
oxdock-buildtime-helpers.workspace = true
oxdock-core = { workspace = true }
oxdock-embed.workspace = true
oxdock-fs.workspace = true
oxdock-parser = { workspace = true, features = ["proc-macro-api"] }
oxdock-process = { workspace = true }
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
oxdock-sys-test-utils.workspace = true
