[package]
name = "oxdock-func-macro"
description = "Host export attribute macros for OxDock DSL native and host functions and types."
categories = ["development-tools::procedural-macro-helpers"]
keywords = ["macros", "oxdock", "marshaling"]
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lints]
workspace = true
