use anyhow::{Context, Result};
use oxdock_core::startup_descriptors;
use oxdock_core::{ArgType, CommandMeta, all_metadata, all_structural_metadata};
use oxdock_core::{FuncMeta, FuncParam, TypeDescriptor, builtin_function_metas};
use std::collections::HashSet;

/// GitHub heading anchor for a `### NAME` section: lowercase. Command names
/// are `[A-Z_]+`, so lowercasing is the whole transformation.
fn index_anchor(name: &str) -> String {
    name.to_lowercase()
}

/// Escape pipe characters so `|` alternatives in syntax strings do not
/// break the enclosing Markdown table.
fn escape_table_cell(s: &str) -> String {
    s.replace('|', "\\|")
}

/// Escape placeholders in emitted prose and examples so the reference
/// passes through the strict downstream EXPAND that renders it and
/// comes out byte-identical for the conformance runner.
/// Already-escaped openers are left alone; registry metadata carries no
/// render-time pins.
fn escape_placeholders(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    // Every opener gains one escape level so the downstream EXPAND resolves
    // exactly one and the rendered bytes match the registry source: a run
    // of n backslashes before `{{` becomes 2n+1, so `\{{` (an escape the
    // conformance runner must execute) renders back identically instead of
    // being consumed early.
    while let Some(pos) = rest.find("{{") {
        let (head, tail) = rest.split_at(pos);
        out.push_str(head);
        let backslashes = head.len() - head.trim_end_matches('\\').len();
        for _ in 0..backslashes + 1 {
            out.push('\\');
        }
        out.push_str("{{");
        rest = &tail[2..];
    }
    out.push_str(rest);
    out
}

/// Generate the command index table from the same metadata registry as
/// the reference body, so the index can never list a removed command
/// (e.g. the stale `RUN_BG` row) or miss a new one.
pub(crate) fn render_index() -> String {
    let mut out = String::new();
    out.push_str(
        "<!-- GENERATED by docs-gen from oxdock-parser metadata. Do not edit by hand. -->\n",
    );
    out.push_str("## Command Reference\n\n");
    out.push_str(
        "See the [changelog]({{ $docs_global.changelog_url }}) for what changed in each release.\n\n",
    );
    out.push_str("| Command | Syntax |\n");
    out.push_str("| --- | --- |\n");
    for meta in all_metadata() {
        out.push_str(&format!(
            "| [`{}`](#{}) | `{}` |\n",
            meta.name,
            index_anchor(meta.name),
            escape_table_cell(meta.syntax),
        ));
    }
    out
}

/// Render one argument type cell: canonical types link to the Value types
/// reference; inline alternations stay plain (they are self-describing).
/// Pipes are escaped so `|` alternations cannot split table rows.
fn render_arg_type(arg_type: &ArgType) -> String {
    let label = escape_table_cell(&arg_type.label());
    match arg_type.anchor() {
        Some(anchor) => format!("[`{label}`](#{anchor})"),
        None => format!("`{label}`"),
    }
}

/// Value type reference, generated from the startup descriptors, so the
/// documented types cannot drift from the type system.
/// Argument shapes (`$var`, `KEY=value`) are not value types: they render
/// unlinked in argument tables (like inline `OneOf` alternations) and are
/// documented where they are used (LET, MUTATION, ENV).
fn render_value_types() -> String {
    let mut out = String::new();
    out.push_str("## Value types\n\n");
    for (name, descriptor) in startup_descriptors() {
        out.push_str(&format!(
            "### {}\n\n{}\n\n",
            escape_placeholders(&format!("Value type: {name}")),
            escape_placeholders(descriptor.docs),
        ));
    }
    out.push('\n');
    out
}

fn render_meta(meta: &CommandMeta) -> Result<String> {
    let mut out = String::new();
    out.push_str(&format!("### {}\n\n", meta.name));
    out.push_str(&format!("{}\n\n", escape_placeholders(meta.summary)));
    out.push_str(&format!("**Syntax:** `{}`\n\n", meta.syntax));

    if !meta.description.is_empty() {
        out.push_str(&format!("{}\n\n", escape_placeholders(meta.description)));
    }

    if !meta.args.is_empty() {
        out.push_str("**Arguments:**\n\n");
        out.push_str("| Name | Type | Required | Description |\n");
        out.push_str("| --- | --- | --- | --- |\n");
        for arg in meta.args {
            let req = if arg.required { "yes" } else { "no" };
            // Escape pipes so `|` alternations in type strings (e.g.
            // `SNAPSHOT|LOCAL`) cannot split the row into extra columns
            // on renderers without GitHub's code-span table handling.
            // Canonical types link to the Value types reference below.
            out.push_str(&format!(
                "| `{}` | {} | {} | {} |\n",
                escape_table_cell(arg.name),
                render_arg_type(&arg.arg_type),
                req,
                escape_table_cell(&escape_placeholders(arg.description))
            ));
        }
        out.push('\n');
    }

    if !meta.flags.is_empty() {
        out.push_str("**Flags:**\n\n");
        out.push_str("| Flag | Type | Description |\n");
        out.push_str("| --- | --- | --- |\n");
        for flag in meta.flags {
            out.push_str(&format!(
                "| `{}` | `{}` | {} |\n",
                escape_table_cell(flag.long),
                flag.value_type.label(),
                escape_table_cell(&escape_placeholders(flag.description))
            ));
        }
        out.push('\n');
    }

    if let Some(stream) = meta.default_output {
        out.push_str(&format!("**Output:** {:?}\n\n", stream));
    }

    if !meta.examples.is_empty() {
        out.push_str("**Examples:**\n\n");
        for example in meta.examples {
            out.push_str(&format!("**Example: {}**\n\n", example.name));
            let fence = example
                .fence_meta
                .map_or_else(|| "oxdock".to_string(), |m| format!("oxdock {m}"));
            out.push_str(&format!(
                "```{}\n{}\n```\n\n",
                fence,
                escape_placeholders(example.code.trim_end())
            ));
            // Fences that must fail carry their needle in the info string
            // (invisible once rendered), so print it as prose: readers see
            // the expected error, and the conformance runner pins it.
            if let Some(fence_meta) = example.fence_meta {
                let needle = oxdock_parser::expect_error_from_info(&format!("oxdock {fence_meta}"))
                    .with_context(|| {
                        format!("example '{}' has malformed fence metadata", example.name)
                    })?;
                if let Some(needle) = needle {
                    out.push_str(&format!(
                        "**Expected error:** `{}`\n\n",
                        escape_placeholders(&needle)
                    ));
                }
            }
        }
    }

    out.push('\n');
    Ok(out)
}

pub(crate) fn render_body() -> Result<String> {
    let mut out = String::new();

    // Structural constructs (parsed by PEG rules, documented via the
    // structural registry in oxdock-parser : never hardcoded here).
    let structural = all_structural_metadata();
    let structural_names: HashSet<&str> = structural.iter().map(|meta| meta.name).collect();
    for meta in &structural {
        out.push_str(&render_meta(meta).with_context(|| format!("render {}", meta.name))?);
    }

    // Leaf commands (from declare_commands! metadata), excluding anything
    // already rendered above so every entry appears exactly once.
    for meta in all_metadata() {
        if structural_names.contains(meta.name) {
            continue;
        }
        out.push_str(&render_meta(&meta).with_context(|| format!("render {}", meta.name))?);
    }

    out.push_str(&render_value_types());
    while out.ends_with('\n') {
        out.pop();
    }
    out.push('\n');
    Ok(out)
}

/// Render one function signature from its derived metadata:
/// `NAME($param: TYPE, ...) -> RET`. Unconstrained `Value` parameters
/// render bare; absent return types render no arrow.
fn render_signature(meta: &FuncMeta) -> String {
    let params = meta
        .params
        .as_deref()
        .unwrap_or(&[])
        .iter()
        .map(
            |FuncParam { name, param_type }: &FuncParam| match param_type {
                Some(label) => format!("${name}: {label}"),
                None => format!("${name}"),
            },
        )
        .collect::<Vec<_>>()
        .join(", ");
    let returns = meta
        .returns
        .as_deref()
        .map(|label| format!(" -> {label}"))
        .unwrap_or_default();
    format!("{}({}){}", meta.name, params, returns)
}

/// Function reference for one module, generated from its function
/// metadata, so the documented functions cannot drift from the
/// implementation. Staged as its own fragment per plugin README; the
/// STD rendering shares this path through `render_function_reference`.
/// Callable names render verbatim (`MODULE::NAME` for builtins,
/// `MODULE_NAME` for plugin entries, matching the registry).
pub(crate) fn render_plugin_reference(metas: &[FuncMeta], module: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "<!-- GENERATED by docs-gen from {module} function metadata. Do not edit by hand. -->\n",
    ));
    out.push_str("## Functions\n\n");
    out.push_str(
        "Callable as `MODULE::NAME(...)` in expressions (or bare `NAME(...)` \
         with the module imported via `IMPORT`). Introspectable from scripts \
         with `FUNCTIONS()` and `DESCRIBE(name)`.\n\n",
    );
    for meta in metas {
        out.push_str(&format!("### {}\n\n", meta.name));
        out.push_str(&format!(
            "**Signature:** `{}`\n\n",
            escape_table_cell(&render_signature(meta)),
        ));
        out.push_str(&format!(
            "**Contexts:** {}\n\n",
            if meta.rpn { "AST, RPN" } else { "AST only" },
        ));
        // The full docs already open with the summary line: print whichever
        // carries more, never both stacked.
        if meta.docs.starts_with(meta.summary) && !meta.summary.is_empty() {
            out.push_str(&escape_placeholders(&format!("{}\n\n", meta.docs)));
        } else {
            if !meta.summary.is_empty() {
                out.push_str(&escape_placeholders(&format!("{}\n\n", meta.summary)));
            }
            if !meta.docs.is_empty() {
                out.push_str(&escape_placeholders(&format!("{}\n\n", meta.docs)));
            }
        }
    }
    while out.ends_with('\n') {
        out.pop();
    }
    out.push('\n');
    out
}

/// Function reference for the STD builtins: the same renderer plugins
/// share, over the `#[oxdock_func]` registry.
pub(crate) fn render_function_reference() -> String {
    render_plugin_reference(&builtin_function_metas(), "STD")
}

/// Plugin handle types, rendered like the startup value types so anchors
/// stay consistent across references.
pub(crate) fn render_plugin_types(descriptors: &[&TypeDescriptor]) -> String {
    let mut out = String::new();
    out.push_str("## Value types\n\n");
    for descriptor in descriptors {
        out.push_str(&format!(
            "### {}\n\n{}\n\n",
            escape_placeholders(&format!("Value type: {}", descriptor.name)),
            escape_placeholders(descriptor.docs),
        ));
    }
    while out.ends_with('\n') {
        out.pop();
    }
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn body_has_all_commands() {
        let body = render_body().expect("render");
        for meta in all_metadata() {
            assert!(
                body.contains(&format!("### {}", meta.name)),
                "missing section for command {}",
                meta.name
            );
        }
    }

    #[test]
    fn body_has_structural_constructs() {
        // Derived from the registry : not a hardcoded list : so adding a
        // structural entry automatically extends this check.
        let body = render_body().expect("render");
        for meta in all_structural_metadata() {
            assert!(
                body.contains(&format!("### {}", meta.name)),
                "missing section for structural construct {}",
                meta.name
            );
        }
    }

    #[test]
    fn failing_examples_render_their_expected_error() {
        // Fences that must fail carry the needle only in the info string,
        // which renderers hide: the prose line below is what readers see.
        let body = render_body().expect("render");
        assert!(
            body.contains("**Expected error:** `undefined variable`"),
            "LET no-hoisting example must print its needle"
        );
        assert!(
            body.contains("**Expected error:** `EXIT requested with code 0`"),
            "EXIT example must print its needle"
        );
    }

    #[test]
    fn metadata_names_are_unique() {
        // A command registered in both the leaf and structural registries
        // would render twice (or be shadowed by the skip filter). Structural
        // entries must live in exactly one registry.
        let mut seen = HashSet::new();
        for meta in all_metadata() {
            assert!(
                seen.insert(meta.name),
                "duplicate metadata entry for {}",
                meta.name
            );
        }
    }

    #[test]
    fn escape_table_cell_escapes_pipes() {
        assert_eq!(
            escape_table_cell("WORKSPACE SNAPSHOT|LOCAL"),
            "WORKSPACE SNAPSHOT\\|LOCAL"
        );
        assert_eq!(escape_table_cell("RUN <command...>"), "RUN <command...>");
    }

    #[test]
    fn index_lists_every_command_exactly_once() {
        // The index table is the drift detector for the command list: a
        // removed command must disappear and a new one must appear, with no
        // hand-maintained rows to forget.
        let body = render_index();
        for meta in all_metadata() {
            let row = format!("| [`{}`](#{}) |", meta.name, index_anchor(meta.name));
            assert!(
                body.matches(&row).count() == 1,
                "index must list {} exactly once",
                meta.name
            );
        }
        assert!(
            !body.contains("RUN_BG"),
            "index must not contain removed commands"
        );
    }

    #[test]
    fn function_reference_covers_every_builtin() {
        // Derived from the `#[oxdock_func]` registry, not a hardcoded
        // list, so adding a builtin automatically extends this check.
        let reference = render_function_reference();
        for meta in builtin_function_metas() {
            assert!(
                reference.contains(&format!("### {}", meta.name)),
                "missing section for function {}",
                meta.name
            );
            assert!(
                reference.contains(&render_signature(&meta)),
                "missing signature for function {}",
                meta.name
            );
        }
        for name in [
            "STD::TYPES",
            "STD::TYPE_DESCRIBE",
            "STD::FUNCTIONS",
            "STD::DESCRIBE",
            "STD::GLOB",
        ] {
            assert!(
                reference.contains(&format!("### {name}")),
                "function reference must document {name}",
            );
        }
        let glob = reference
            .split("### STD::GLOB")
            .nth(1)
            .expect("GLOB section renders");
        assert!(
            glob.contains("**Contexts:** AST, RPN"),
            "RPN-capable functions must render both contexts",
        );
        let types = reference
            .split("### STD::TYPES\n")
            .nth(1)
            .expect("TYPES section renders");
        assert!(
            types.contains("**Contexts:** AST only"),
            "AST-only functions must render their restriction",
        );
    }
}
