use anyhow::Result;
use oxdock_core::{ArgType, CommandMeta, all_metadata, all_structural_metadata};
use oxdock_fs::{GuardedPath, PathResolver};
use oxdock_parser::TypeKind;
use std::collections::HashSet;

use crate::io::write_text;

/// Refresh the committed command-reference inputs from the parser
/// registry, so generated docs can never list a removed command.
pub(crate) fn sync_command_ref(root: &GuardedPath, resolver: &PathResolver) -> Result<()> {
    write_text(
        resolver,
        root,
        ".oxdock/template/readme/generated/command-reference.md.tmpl",
        &render_index(),
    )?;
    write_text(
        resolver,
        root,
        ".oxdock/template/readme/generated/command-body.md.tmpl",
        &render_body(),
    )
}

/// GitHub heading anchor for a `### NAME` section: lowercase. Command names
/// are `[A-Z_]+`, so lowercasing is the whole transformation.
fn index_anchor(name: &str) -> String {
    name.to_lowercase()
}

/// Escape pipe characters so `|` alternatives in syntax strings do not
/// break the enclosing Markdown table.
fn escape_table_cell(s: &str) -> String {
    s.replace('|', "\\|")
}

/// Escape placeholders in emitted prose and examples so the reference
/// passes through the strict downstream EXPAND that renders it and
/// comes out byte-identical for the conformance runner.
/// Already-escaped openers are left alone; registry metadata carries no
/// render-time pins.
fn escape_placeholders(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    // Every opener gains one escape level so the downstream EXPAND resolves
    // exactly one and the rendered bytes match the registry source: a run
    // of n backslashes before `{{` becomes 2n+1, so `\{{` (an escape the
    // conformance runner must execute) renders back identically instead of
    // being consumed early.
    while let Some(pos) = rest.find("{{") {
        let (head, tail) = rest.split_at(pos);
        out.push_str(head);
        let backslashes = head.len() - head.trim_end_matches('\\').len();
        for _ in 0..backslashes + 1 {
            out.push('\\');
        }
        out.push_str("{{");
        rest = &tail[2..];
    }
    out.push_str(rest);
    out
}

/// Generate the command index table from the same metadata registry as
/// the reference body, so the index can never list a removed command
/// (e.g. the stale `RUN_BG` row) or miss a new one.
pub(crate) fn render_index() -> String {
    let mut out = String::new();
    out.push_str(
        "<!-- GENERATED by docs-gen from oxdock-parser metadata. Do not edit by hand. -->\n",
    );
    out.push_str("## Command Reference\n\n");
    out.push_str("| Command | Syntax |\n");
    out.push_str("| --- | --- |\n");
    for meta in all_metadata() {
        out.push_str(&format!(
            "| [`{}`](#{}) | `{}` |\n",
            meta.name,
            index_anchor(meta.name),
            escape_table_cell(meta.syntax),
        ));
    }
    out
}

/// Render one argument type cell: canonical types link to the Value types
/// reference; inline alternations stay plain (they are self-describing).
/// Pipes are escaped so `|` alternations cannot split table rows.
fn render_arg_type(arg_type: &ArgType) -> String {
    let label = escape_table_cell(&arg_type.label());
    match arg_type.anchor() {
        Some(anchor) => format!("[`{label}`](#{anchor})"),
        None => format!("`{label}`"),
    }
}

/// Value type reference, generated from the `TypeKind` declaration-site
/// vocabulary, so the documented types cannot drift from the type system.
/// Argument shapes (`$var`, `KEY=value`) are not value types: they render
/// unlinked in argument tables (like inline `OneOf` alternations) and are
/// documented where they are used (LET, MUTATION, ENV).
fn render_value_types() -> String {
    let mut out = String::new();
    out.push_str("## Value types\n\n");
    for kind in TypeKind::CANONICAL {
        let Some((title, body)) = kind.doc() else {
            continue;
        };
        out.push_str(&format!(
            "### {}\n\n{}\n\n",
            escape_placeholders(&title),
            escape_placeholders(body)
        ));
    }
    out.push('\n');
    out
}

fn render_meta(meta: &CommandMeta) -> String {
    let mut out = String::new();
    out.push_str(&format!("### {}\n\n", meta.name));
    out.push_str(&format!("{}\n\n", escape_placeholders(meta.summary)));
    out.push_str(&format!("**Syntax:** `{}`\n\n", meta.syntax));

    if !meta.description.is_empty() {
        out.push_str(&format!("{}\n\n", escape_placeholders(meta.description)));
    }

    if !meta.args.is_empty() {
        out.push_str("**Arguments:**\n\n");
        out.push_str("| Name | Type | Required | Description |\n");
        out.push_str("| --- | --- | --- | --- |\n");
        for arg in meta.args {
            let req = if arg.required { "yes" } else { "no" };
            // Escape pipes so `|` alternations in type strings (e.g.
            // `SNAPSHOT|LOCAL`) cannot split the row into extra columns
            // on renderers without GitHub's code-span table handling.
            // Canonical types link to the Value types reference below.
            out.push_str(&format!(
                "| `{}` | {} | {} | {} |\n",
                escape_table_cell(arg.name),
                render_arg_type(&arg.arg_type),
                req,
                escape_table_cell(&escape_placeholders(arg.description))
            ));
        }
        out.push('\n');
    }

    if !meta.flags.is_empty() {
        out.push_str("**Flags:**\n\n");
        out.push_str("| Flag | Type | Description |\n");
        out.push_str("| --- | --- | --- |\n");
        for flag in meta.flags {
            out.push_str(&format!(
                "| `{}` | `{}` | {} |\n",
                escape_table_cell(flag.long),
                flag.value_type.label(),
                escape_table_cell(&escape_placeholders(flag.description))
            ));
        }
        out.push('\n');
    }

    if let Some(stream) = meta.default_output {
        out.push_str(&format!("**Output:** {:?}\n\n", stream));
    }

    if !meta.examples.is_empty() {
        out.push_str("**Examples:**\n\n");
        for example in meta.examples {
            out.push_str(&format!("**Example: {}**\n\n", example.name));
            let fence = example
                .fence_meta
                .map_or_else(|| "oxdock".to_string(), |m| format!("oxdock {m}"));
            out.push_str(&format!(
                "```{}\n{}\n```\n\n",
                fence,
                escape_placeholders(example.code.trim_end())
            ));
        }
    }

    out.push('\n');
    out
}

pub(crate) fn render_body() -> String {
    let mut out = String::new();

    // Structural constructs (parsed by PEG rules, documented via the
    // structural registry in oxdock-parser — never hardcoded here).
    let structural = all_structural_metadata();
    let structural_names: HashSet<&str> = structural.iter().map(|meta| meta.name).collect();
    for meta in &structural {
        out.push_str(&render_meta(meta));
    }

    // Leaf commands (from declare_commands! metadata), excluding anything
    // already rendered above so every entry appears exactly once.
    for meta in all_metadata() {
        if structural_names.contains(meta.name) {
            continue;
        }
        out.push_str(&render_meta(&meta));
    }

    out.push_str(&render_value_types());
    while out.ends_with('\n') {
        out.pop();
    }
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn body_has_all_commands() {
        let body = render_body();
        for meta in all_metadata() {
            assert!(
                body.contains(&format!("### {}", meta.name)),
                "missing section for command {}",
                meta.name
            );
        }
    }

    #[test]
    fn body_has_structural_constructs() {
        // Derived from the registry — not a hardcoded list — so adding a
        // structural entry automatically extends this check.
        let body = render_body();
        for meta in all_structural_metadata() {
            assert!(
                body.contains(&format!("### {}", meta.name)),
                "missing section for structural construct {}",
                meta.name
            );
        }
    }

    #[test]
    fn metadata_names_are_unique() {
        // A command registered in both the leaf and structural registries
        // would render twice (or be shadowed by the skip filter). Structural
        // entries must live in exactly one registry.
        let mut seen = HashSet::new();
        for meta in all_metadata() {
            assert!(
                seen.insert(meta.name),
                "duplicate metadata entry for {}",
                meta.name
            );
        }
    }

    #[test]
    fn escape_table_cell_escapes_pipes() {
        assert_eq!(
            escape_table_cell("WORKSPACE SNAPSHOT|LOCAL"),
            "WORKSPACE SNAPSHOT\\|LOCAL"
        );
        assert_eq!(escape_table_cell("RUN <command...>"), "RUN <command...>");
    }

    #[test]
    fn index_lists_every_command_exactly_once() {
        // The index table is the drift detector for the command list: a
        // removed command must disappear and a new one must appear, with no
        // hand-maintained rows to forget.
        let body = render_index();
        for meta in all_metadata() {
            let row = format!("| [`{}`](#{}) |", meta.name, index_anchor(meta.name));
            assert!(
                body.matches(&row).count() == 1,
                "index must list {} exactly once",
                meta.name
            );
        }
        assert!(
            !body.contains("RUN_BG"),
            "index must not contain removed commands"
        );
    }
}
