[package]
name = "oxdock-doc-tests"
description = "Executes README.md Rust examples as doctests."
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[package.metadata.cargo-udeps.ignore]
development = ["oxdock-macros"]

[dev-dependencies]
oxdock-macros.workspace = true
