use anyhow::{Context, Result};
use oxdock_core::startup_descriptors;
use oxdock_core::{ArgType, CommandMeta, all_metadata, all_structural_metadata};
use oxdock_core::{FuncMeta, FuncParam, TypeDescriptor, TypeTag, builtin_function_metas};
use oxdock_markdown_plugin::markdown::escape_table_cell;
use std::collections::HashSet;

/// GitHub heading anchor for a `### NAME` section: lowercase. Command names
/// are `[A-Z_]+`, so lowercasing is the whole transformation.
fn index_anchor(name: &str) -> String {
    name.to_lowercase()
}

/// Escape placeholders in emitted prose and examples so the reference
/// passes through the strict downstream EXPAND that renders it and
/// comes out byte-identical for the conformance runner.
/// Already-escaped openers are left alone; registry metadata carries no
/// render-time pins.
fn escape_placeholders(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    // Every opener gains one escape level so the downstream EXPAND resolves
    // exactly one and the rendered bytes match the registry source: a run
    // of n backslashes before `{{` becomes 2n+1, so `\{{` (an escape the
    // conformance runner must execute) renders back identically instead of
    // being consumed early.
    while let Some(pos) = rest.find("{{") {
        let (head, tail) = rest.split_at(pos);
        out.push_str(head);
        let backslashes = head.len() - head.trim_end_matches('\\').len();
        for _ in 0..backslashes + 1 {
            out.push('\\');
        }
        out.push_str("{{");
        rest = &tail[2..];
    }
    out.push_str(rest);
    out
}

/// Generate the command index table from the same metadata registry as
/// the reference body, so the index can never list a removed command
/// (e.g. the stale `RUN_BG` row) or miss a new one.
pub(crate) fn render_index() -> String {
    let mut out = String::new();
    out.push_str(
        "<!-- GENERATED by docs-gen from oxdock-parser metadata. Do not edit by hand. -->\n",
    );
    out.push_str("## Command Reference\n\n");
    out.push_str(
        "See the [changelog]({{ $docs_global.changelog_url }}) for what changed in each release.\n\n",
    );
    out.push_str("| Command | Syntax |\n");
    out.push_str("| --- | --- |\n");
    for meta in all_metadata() {
        out.push_str(&format!(
            "| [`{}`](#{}) | `{}` |\n",
            meta.name,
            index_anchor(meta.name),
            escape_table_cell(meta.syntax),
        ));
    }
    out
}

/// Render one argument type cell: canonical types link to the Value types
/// reference; inline alternations stay plain (they are self-describing).
/// Pipes are escaped so `|` alternations cannot split table rows.
fn render_arg_type(arg_type: &ArgType) -> String {
    let label = escape_table_cell(&arg_type.label());
    match arg_type.anchor() {
        Some(anchor) => format!("[`{label}`](#{anchor})"),
        None => format!("`{label}`"),
    }
}

/// Value type reference, generated from the startup descriptors, so the
/// documented types cannot drift from the type system.
/// Argument shapes (`$var`, `KEY=value`) are not value types: they render
/// unlinked in argument tables (like inline `OneOf` alternations) and are
/// documented where they are used (LET, MUTATION, ENV).
fn render_value_types() -> String {
    let mut out = String::new();
    out.push_str("## Value types\n\n");
    for (name, descriptor) in startup_descriptors() {
        out.push_str(&format!(
            "### {}\n\n{}\n\n",
            escape_placeholders(&format!("Value type: {name}")),
            escape_placeholders(descriptor.docs),
        ));
    }
    out.push('\n');
    out
}

fn render_meta(meta: &CommandMeta) -> Result<String> {
    let mut out = String::new();
    out.push_str(&format!("### {}\n\n", meta.name));
    out.push_str(&format!("{}\n\n", escape_placeholders(meta.summary)));
    out.push_str(&format!("**Syntax:** `{}`\n\n", meta.syntax));

    if !meta.description.is_empty() {
        out.push_str(&format!("{}\n\n", escape_placeholders(meta.description)));
    }

    if !meta.args.is_empty() {
        out.push_str("**Arguments:**\n\n");
        out.push_str("| Name | Type | Required | Description |\n");
        out.push_str("| --- | --- | --- | --- |\n");
        for arg in meta.args {
            let req = if arg.required { "yes" } else { "no" };
            // Escape pipes so `|` alternations in type strings (e.g.
            // `SNAPSHOT|LOCAL`) cannot split the row into extra columns
            // on renderers without GitHub's code-span table handling.
            // Canonical types link to the Value types reference below.
            out.push_str(&format!(
                "| `{}` | {} | {} | {} |\n",
                escape_table_cell(arg.name),
                render_arg_type(&arg.arg_type),
                req,
                escape_table_cell(&escape_placeholders(arg.description))
            ));
        }
        out.push('\n');
    }

    if !meta.flags.is_empty() {
        out.push_str("**Flags:**\n\n");
        out.push_str("| Flag | Type | Description |\n");
        out.push_str("| --- | --- | --- |\n");
        for flag in meta.flags {
            out.push_str(&format!(
                "| `{}` | `{}` | {} |\n",
                escape_table_cell(flag.long),
                flag.value_type.label(),
                escape_table_cell(&escape_placeholders(flag.description))
            ));
        }
        out.push('\n');
    }

    if let Some(stream) = meta.default_output {
        out.push_str(&format!("**Output:** {:?}\n\n", stream));
    }

    if !meta.examples.is_empty() {
        out.push_str("**Examples:**\n\n");
        for example in meta.examples {
            out.push_str(&format!("**Example: {}**\n\n", example.name));
            let fence = example
                .fence_meta
                .map_or_else(|| "oxdock".to_string(), |m| format!("oxdock {m}"));
            out.push_str(&format!(
                "```{}\n{}\n```\n\n",
                fence,
                escape_placeholders(example.code.trim_end())
            ));
            // Fences that must fail carry their needle in the info string
            // (invisible once rendered), so print it as prose: readers see
            // the expected error, and the conformance runner pins it.
            if let Some(fence_meta) = example.fence_meta {
                let needle = oxdock_parser::expect_error_from_info(&format!("oxdock {fence_meta}"))
                    .with_context(|| {
                        format!("example '{}' has malformed fence metadata", example.name)
                    })?;
                if let Some(needle) = needle {
                    out.push_str(&format!(
                        "**Expected error:** `{}`\n\n",
                        escape_placeholders(&needle)
                    ));
                }
            }
        }
    }

    out.push('\n');
    Ok(out)
}

pub(crate) fn render_body() -> Result<String> {
    let mut out = String::new();

    // Structural constructs (parsed by PEG rules, documented via the
    // structural registry in oxdock-parser : never hardcoded here).
    let structural = all_structural_metadata();
    let structural_names: HashSet<&str> = structural.iter().map(|meta| meta.name).collect();
    for meta in &structural {
        out.push_str(&render_meta(meta).with_context(|| format!("render {}", meta.name))?);
    }

    // Leaf commands (from declare_commands! metadata), excluding anything
    // already rendered above so every entry appears exactly once.
    for meta in all_metadata() {
        if structural_names.contains(meta.name) {
            continue;
        }
        out.push_str(&render_meta(&meta).with_context(|| format!("render {}", meta.name))?);
    }

    out.push_str(&render_value_types());
    while out.ends_with('\n') {
        out.pop();
    }
    out.push('\n');
    Ok(out)
}

/// Render one function signature from its derived metadata:
/// `NAME($param: TYPE, ...) -> RET`. Every parameter renders its
/// type (bare `Value` is `ANY`, never a hole); absent return types
/// render no arrow. Closed `#[values]` sets render after the type
/// (`$policy: STRING = a | b`), generated from the same tokens as
/// the extractor check. Options-bearing `MAP` parameters render
/// their known keys in record form (`MAP<timeout?: DURATION>`),
/// the same grammar record returns use.
fn render_signature(meta: &FuncMeta) -> String {
    let params = meta
        .params
        .as_deref()
        .unwrap_or(&[])
        .iter()
        .map(|param| {
            let rendered = render_param_type(param);
            match param.param_type.as_ref().zip(param.allowed.as_ref()) {
                Some((_, values)) => {
                    format!("${}: {} = {}", param.name, rendered, values.join(" | "))
                }
                None => format!("${}: {}", param.name, rendered),
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let returns = meta
        .returns
        .as_ref()
        .map(|tag| format!(" -> {}", render_tag(tag)))
        .unwrap_or_default();
    format!("{}({}){}", meta.name, params, returns)
}

/// Render one parameter's type: options-bearing `MAP` params name
/// their known keys in the record grammar (`MAP<timeout?: DURATION>`,
/// defaults in nested bullets only), everything else renders its tag
/// structurally. Single source for signatures and parameter bullets,
/// so the two can never disagree.
fn render_param_type(param: &FuncParam) -> String {
    if let Some(keys) = param.options
        && !keys.is_empty()
    {
        let rendered = keys
            .iter()
            .map(|key| {
                format!(
                    "{}{}: {}",
                    key.name,
                    if key.required { "" } else { "?" },
                    render_tag(&key.value),
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        return format!("MAP<{rendered}>");
    }
    param
        .param_type
        .as_ref()
        .map(render_tag)
        .unwrap_or_default()
}

/// Render one tag structurally: shaped tags name their contents
/// (`LIST<MAP>`, `MAP<name: TYPE, ...>`), so the signature shows the
/// generics the extractor enforces instead of the coarse word kind.
/// Single renderer shared with the core (`DESCRIBE` output).
fn render_tag(tag: &TypeTag) -> String {
    oxdock_parser::render_structural(tag)
}

/// Render one function's parameter docs: a bullet per parameter with
/// its structural type, plus nested bullets for options keys, plus a
/// returns block naming the return shape and every record field.
/// Bullets derive entirely from typed metadata (names, tags, allowed
/// sets, options keys, return shapes); per-parameter prose, when the
/// author wrote `///` docs on the parameter itself, appends after a
/// colon. Structure never depends on prose, so nothing can vary.
fn render_parameters(meta: &FuncMeta) -> String {
    let params = meta.params.as_deref().unwrap_or(&[]);
    let mut bullets = Vec::new();
    for param in params {
        let mut bullet = format!("- `${}` ({})", param.name, render_param_type(param));
        if !param.docs.is_empty() {
            bullet.push_str(&format!(": {}", escape_placeholders(param.docs)));
        }
        if let Some(keys) = param.options {
            for key in keys.iter() {
                bullet.push_str(&format!(
                    "\n  - `{}` ({}, {}{})",
                    key.name,
                    render_tag(&key.value),
                    if key.required { "required" } else { "optional" },
                    key.default
                        .map(|default| format!(", default `{default}`"))
                        .unwrap_or_default(),
                ));
            }
        }
        bullets.push(bullet);
    }
    let mut sections = Vec::new();
    if !bullets.is_empty() {
        sections.push(format!("**Parameters:**\n{}", bullets.join("\n")));
    }
    if let Some(returns) = meta.returns.as_ref() {
        sections.push(render_returns(returns));
    }
    if sections.is_empty() {
        return String::new();
    }
    format!("{}\n\n", sections.join("\n\n"))
}

/// Render one function's return shape: the structural type plus a
/// nested bullet per record field (optional marks included). Derived
/// entirely from the return tag, like parameters: fixed-shape
/// returns document every property, unknown shapes render bare.
fn render_returns(returns: &TypeTag) -> String {
    let mut out = format!("**Returns:** `{}`", render_tag(returns));
    if let TypeTag::Record(fields) = returns {
        for field in fields.iter() {
            out.push_str(&format!(
                "\n  - `{}` ({}{})",
                field.name,
                render_tag(&field.ty),
                if field.optional { ", optional" } else { "" },
            ));
            if !field.docs.is_empty() {
                out.push_str(&format!(": {}", escape_placeholders(field.docs)));
            }
        }
    }
    out
}

/// Function reference for one module, generated from its function
/// metadata, so the documented functions cannot drift from the
/// implementation. Staged as its own fragment per plugin README; the
/// STD rendering shares this path through `render_function_reference`.
/// Callable names render verbatim (`MODULE::NAME` for builtins,
/// `MODULE_NAME` for plugin entries, matching the registry).
pub(crate) fn render_plugin_reference(metas: &[FuncMeta], module: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "<!-- GENERATED by docs-gen from {module} function metadata. Do not edit by hand. -->\n",
    ));
    out.push_str("## Functions\n\n");
    out.push_str(
        "Callable as `MODULE::NAME(...)` in expressions (or bare `NAME(...)` \
         with the module imported via `IMPORT`). Introspectable from scripts \
         with `FUNCTIONS()` and `DESCRIBE(name)`.\n\n",
    );
    for meta in metas {
        out.push_str(&format!("### {}\n\n", meta.name));
        // No cell escaping: the signature renders inside backticks,
        // which already isolate `|` from table parsing. Escaping here
        // would print a literal backslash (closed `#[values]` sets
        // render `a | b`).
        out.push_str(&format!("**Signature:** `{}`\n\n", render_signature(meta)));
        out.push_str(&format!(
            "**Contexts:** {}\n\n",
            if meta.rpn { "AST, RPN" } else { "AST only" },
        ));
        out.push_str(&render_parameters(meta));
        // The full docs already open with the summary line: print whichever
        // carries more, never both stacked.
        if meta.docs.starts_with(meta.summary) && !meta.summary.is_empty() {
            out.push_str(&escape_placeholders(&format!("{}\n\n", meta.docs)));
        } else {
            if !meta.summary.is_empty() {
                out.push_str(&escape_placeholders(&format!("{}\n\n", meta.summary)));
            }
            if !meta.docs.is_empty() {
                out.push_str(&escape_placeholders(&format!("{}\n\n", meta.docs)));
            }
        }
    }
    while out.ends_with('\n') {
        out.pop();
    }
    out.push('\n');
    out
}

/// Function reference for the STD builtins: the same renderer plugins
/// share, over the `#[oxdock_func]` registry.
pub(crate) fn render_function_reference() -> String {
    render_plugin_reference(&builtin_function_metas(), "STD")
}

/// Plugin handle types, rendered like the startup value types so anchors
/// stay consistent across references. Minted-by and consumed-by lists
/// derive from function metadata (record returns carrying the handle,
/// parameters taking it), so the lifecycle story cannot rot apart from
/// the signatures that enforce it.
pub(crate) fn render_plugin_types(descriptors: &[&TypeDescriptor], metas: &[FuncMeta]) -> String {
    let mut out = String::new();
    out.push_str("## Value types\n\n");
    for descriptor in descriptors {
        out.push_str(&format!(
            "### {}\n\n{}\n\n",
            escape_placeholders(&format!("Value type: {}", descriptor.name)),
            escape_placeholders(descriptor.docs),
        ));
        let mut minted: Vec<&str> = Vec::new();
        let mut consumed: Vec<&str> = Vec::new();
        for meta in metas {
            if meta
                .returns
                .as_ref()
                .is_some_and(|returns| tag_mentions(returns, descriptor))
            {
                minted.push(meta.name.as_str());
            }
            let takes = meta
                .params
                .as_deref()
                .unwrap_or(&[])
                .iter()
                .filter_map(|param| param.param_type.as_ref())
                .any(|tag| tag_mentions(tag, descriptor));
            if takes {
                consumed.push(meta.name.as_str());
            }
        }
        let mut origins = Vec::new();
        if !minted.is_empty() {
            origins.push(format!("Minted by {}", backticked(&minted)));
        }
        if !consumed.is_empty() {
            origins.push(format!("used by {}", backticked(&consumed)));
        }
        if !origins.is_empty() {
            out.push_str(&format!("{}.\n\n", origins.join("; ")));
        }
    }
    while out.ends_with('\n') {
        out.pop();
    }
    out.push('\n');
    out
}

/// Whether a tag carries a custom handle descriptor, recursing through
/// composites: record returns mint the handles nested in their fields.
fn tag_mentions(tag: &TypeTag, descriptor: &TypeDescriptor) -> bool {
    match tag {
        TypeTag::Custom(other) => std::ptr::eq(*other, descriptor),
        TypeTag::ListOf(inner) | TypeTag::MapOf(inner) => tag_mentions(inner, descriptor),
        TypeTag::Record(fields) => fields
            .iter()
            .any(|field| tag_mentions(&field.ty, descriptor)),
        _ => false,
    }
}

/// Comma-joined backticked names for origin lines.
fn backticked(names: &[&str]) -> String {
    names
        .iter()
        .map(|name| format!("`{name}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn body_has_all_commands() {
        let body = render_body().expect("render");
        for meta in all_metadata() {
            assert!(
                body.contains(&format!("### {}", meta.name)),
                "missing section for command {}",
                meta.name
            );
        }
    }

    #[test]
    fn body_has_structural_constructs() {
        // Derived from the registry : not a hardcoded list : so adding a
        // structural entry automatically extends this check.
        let body = render_body().expect("render");
        for meta in all_structural_metadata() {
            assert!(
                body.contains(&format!("### {}", meta.name)),
                "missing section for structural construct {}",
                meta.name
            );
        }
    }

    #[test]
    fn failing_examples_render_their_expected_error() {
        // Fences that must fail carry the needle only in the info string,
        // which renderers hide: the prose line below is what readers see.
        let body = render_body().expect("render");
        assert!(
            body.contains("**Expected error:** `undefined variable`"),
            "LET no-hoisting example must print its needle"
        );
        assert!(
            body.contains("**Expected error:** `EXIT requested with code 0`"),
            "EXIT example must print its needle"
        );
    }

    #[test]
    fn metadata_names_are_unique() {
        // A command registered in both the leaf and structural registries
        // would render twice (or be shadowed by the skip filter). Structural
        // entries must live in exactly one registry.
        let mut seen = HashSet::new();
        for meta in all_metadata() {
            assert!(
                seen.insert(meta.name),
                "duplicate metadata entry for {}",
                meta.name
            );
        }
    }

    #[test]
    fn escape_table_cell_escapes_pipes() {
        assert_eq!(
            escape_table_cell("WORKSPACE SNAPSHOT|LOCAL"),
            "WORKSPACE SNAPSHOT\\|LOCAL"
        );
        assert_eq!(escape_table_cell("RUN <command...>"), "RUN <command...>");
    }

    #[test]
    fn index_lists_every_command_exactly_once() {
        // The index table is the drift detector for the command list: a
        // removed command must disappear and a new one must appear, with no
        // hand-maintained rows to forget.
        let body = render_index();
        for meta in all_metadata() {
            let row = format!("| [`{}`](#{}) |", meta.name, index_anchor(meta.name));
            assert!(
                body.matches(&row).count() == 1,
                "index must list {} exactly once",
                meta.name
            );
        }
        assert!(
            !body.contains("RUN_BG"),
            "index must not contain removed commands"
        );
    }

    #[test]
    fn function_reference_covers_every_builtin() {
        // Derived from the `#[oxdock_func]` registry, not a hardcoded
        // list, so adding a builtin automatically extends this check.
        let reference = render_function_reference();
        for meta in builtin_function_metas() {
            assert!(
                reference.contains(&format!("### {}", meta.name)),
                "missing section for function {}",
                meta.name
            );
            assert!(
                reference.contains(&render_signature(&meta)),
                "missing signature for function {}",
                meta.name
            );
        }
        for name in [
            "STD::TYPES",
            "STD::TYPE_DESCRIBE",
            "STD::FUNCTIONS",
            "STD::DESCRIBE",
            "STD::GLOB",
        ] {
            assert!(
                reference.contains(&format!("### {name}")),
                "function reference must document {name}",
            );
        }
        let glob = reference
            .split("### STD::GLOB")
            .nth(1)
            .expect("GLOB section renders");
        assert!(
            glob.contains("**Contexts:** AST, RPN"),
            "RPN-capable functions must render both contexts",
        );
        let types = reference
            .split("### STD::TYPES\n")
            .nth(1)
            .expect("TYPES section renders");
        assert!(
            types.contains("**Contexts:** AST only"),
            "AST-only functions must render their restriction",
        );
    }
}
