[package]
name = "oxdock-parser"
description = "Parser and AST definitions for the OxDock DSL."
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[features]
default = []
proc-macro-api = ["proc-macro2", "syn", "quote"]

[dependencies]
anyhow.workspace = true
line-ending.workspace = true
pest.workspace = true
pest_derive.workspace = true
proc-macro2 = { workspace = true, optional = true, features = ["span-locations"] }
pulldown-cmark = { version = "0.13.4", default-features = false }
quote = { workspace = true, optional = true }
syn = { workspace = true, optional = true }

[dev-dependencies]
indoc.workspace = true
